using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("FST")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("<anonymmous>")]
[assembly: AssemblyProduct("FST")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("ab774f0e-70a9-4010-bb7c-26d8e4408d72")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
